version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: deutsche
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: akshay
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: akshaygade23/deutsche-spring-boot:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:8090"
    environment:
#      SERVER_PORT: 8090
#      SERVER_SERVLET_CONTEXT_PATH: /api/v1
#      SPRING_APPLICATION_NAME: deutsche-springboot-demo
#      LOGGING_FILE_NAME: app.log
#      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: 1.0
#      restart: unless-stopped

volumes:
  db_data:
